#默认使用配置
spring:
  profiles:
    active: dev

#公共配置与profiles选择无关
mybatis:
  typeAliasesPackage: com.webvisit.model
  mapperLocations: classpath:mapper/*.xml

# ===================================================================
# 分布式文件系统FDFS配置
# ===================================================================
fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image:             #缩略图生成参数
    width: 150
    height: 150
  tracker-list:            #TrackerList参数,支持多个
    - img.znzn.me:22122
---

#开发配置
spring:
  profiles: dev

  datasource:
    url: jdbc:log4jdbc:mysql://www.znzn.me:3306/webvisit?useUnicode=true&characterEncoding=utf8&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    username: root
    password:
    #不输出日志
    #driver-class-name: com.mysql.cj.jdbc.Driver
    #输出日志
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource

  redis:
    database: 0
    # Redis服务器地址
    host: redis.znzn.me
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
    # 连接池最大连接数（使用负值表示没有限制）
    jedis:
      pool:
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0
    # 连接超时时间（毫秒）
    timeout: 10000

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
